# Generated by Django 5.2.7 on 2025-11-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_invoice_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
