# Generated by Django 5.2.7 on 2025-11-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextlookup',
            name='symbol',
            field=models.CharField(max_length=1),
        ),
    ]
