# Generated by Django 5.2.7 on 2025-11-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_contextlookup_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextmanager',
            name='defaultIfNoRule',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
