# Generated by Django 5.2.7 on 2025-11-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_contextmanager_defaultifnorule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextmanager',
            name='defaultIfNoRule',
            field=models.BooleanField(default=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contextmanager',
            name='defaultXValue',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
