# Generated by Django 5.2.7 on 2025-11-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_contextmanager_defaultifnorule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name_plural': 'Roles'},
        ),
    ]
